seqan/raptor

- .github/workflows/ci.yml
See https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
> [INFRA] add-path is deprecated

- README.md
Blocked by https://github.com/bioconda/bioconda-recipes/pull/24742
> [INFRA] Add bioconda package

- src/raptor.cpp
- test/cli/raptor_test.cpp
At the moment using the threshold option leads to an segfault, this should fix this.
@eseiler 
If you tell me, how you determined the expected results in the cli test, I will create them for the threshold and then add it to the PR.
EDIT: I can't assign a reviewer, is that correct?
> [FIX] Fix threshold option and add test

- CHANGELOG.md
- CMakeLists.txt
- README.md
- src/raptor.cpp
- test/cli/raptor_test.cpp
> [FEATURE] Accept file containing bin paths

- .gitmodules
- src/raptor.cpp
- src/raptor_build.cpp
- src/raptor_main.cpp
- src/raptor_search.cpp
- test/cli/cli_test.hpp
- test/cli/raptor_options_test.cpp
- test/cli/raptor_test.cpp
> [INFRA] Use upstream SeqAn3

- src/raptor.cpp
> [MISC] re-add compression extension handling

- src/raptor.cpp
Resolves https://github.com/seqan/raptor/issues/24
> [FIX] Using wrong validator when checking single input

- .gitattributes
> [MISC] fix language stat exclusion

- include/raptor/argument_parsing/shared.hpp
- include/raptor/raptor.hpp
- include/raptor/shared.hpp
- src/argument_parsing/build.cpp
- src/argument_parsing/search.cpp
- src/argument_parsing/shared.cpp
- src/argument_parsing/upgrade.cpp
- src/raptor_main.cpp
> [FIX] window parameter documentation

- .github/workflows/ci_linux.yml
- .github/workflows/ci_macos.yml
- .github/workflows/ci_misc.yml
- .gitmodules
- CMakeLists.txt
- doc/CMakeLists.txt
- src/CMakeLists.txt
- src/argument_parsing/CMakeLists.txt
- src/build/CMakeLists.txt
- src/build/hibf/CMakeLists.txt
- src/search/CMakeLists.txt
- src/upgrade/CMakeLists.txt
- test/CMakeLists.txt
- test/api/CMakeLists.txt
- test/benchmark/CMakeLists.txt
- test/cli/CMakeLists.txt
- test/cli/argument_parsing/CMakeLists.txt
- test/cli/build/CMakeLists.txt
- test/cli/build/cli_build_from_chopper_test.cpp
- test/cli/search/CMakeLists.txt
- test/cli/upgrade/CMakeLists.txt
- test/coverage/CMakeLists.txt
- test/data/datasources.cmake
- test/header/CMakeLists.txt
- util/CMakeLists.txt
- util/thresholding/CMakeLists.txt
Supersedes https://github.com/seqan/raptor/pull/106
> [INFRA] Use chopper submodule

- test/cli/build/cli_build_from_chopper_test.cpp
- test/cli/build/cli_build_ibf_compressed_test.cpp
- test/cli/build/cli_build_ibf_partitioned_test.cpp
- test/cli/build/cli_build_ibf_test.cpp
- test/cli/cli_test.hpp
- test/cli/search/cli_search_ibf_preprocessing_test.cpp
- test/cli/upgrade/cli_upgrade_test.cpp
Working on a pipeline test for chopper and noticed a lot of repeated code :)
> [TEST] Small test refactoring.

- src/search/precompute_threshold.cpp
- util/thresholding/include/minimizer_model.hpp
- util/thresholding/src/query.cpp
> [FIX] wrong lower bound for minimizer counts

- src/build/hibf/parse_chopper_pack_header.cpp
- test/cli/build/cli_build_hibf_chopper_test.cpp
Right now raptor and chopper diverge and you cannot build from current chopper layouts. This fixes it.
Basically adapts reading layout files to PR https://github.com/seqan/chopper/pull/83
> [FEATURE] Update chopper to current master and adapt layout reading.

- src/build/compute_minimiser.cpp
The thresholds hold for equal as well.
> [FIX] Correct cutoff calculation.

- workflow/nextflow/README.md
- workflow/nextflow/hibf.nf
Might need some more sentences in the README (wasn't up-to-date before anyway)
> [INFRA] Move database to FTP

- .github/workflows/ci_misc.yml
- include/raptor/hierarchical_interleaved_bloom_filter.hpp
- include/raptor/index.hpp
- test/documentation/raptor_doxygen_cfg.in
Update doxygen config, fix unresolved references and ignore undocumented members.
> [DOC] Doxygen: remove some warnings

- src/argument_parsing/build_parsing.cpp
- src/argument_parsing/search_parsing.cpp
- src/argument_parsing/upgrade_parsing.cpp
Resolves https://github.com/seqan/raptor/issues/171
> [DOC] Add descriptions for subparsers

- doc/setup/quickstart_cmake/index.md
- doc/tutorial/01_introduction/index.md
Mostly copied from the main README page. 
I have added two introductory sentences and links about minimisers in seqan3.
> [DOC] Add an introductional tutorial page.

- include/raptor/search/search_singular_ibf.hpp
- include/raptor/search/sync_out.hpp
- src/search/search_partitioned_ibf.cpp
- test/include/raptor/test/cli_test.hpp
Resolves https://github.com/seqan/raptor/issues/156
> [FEATURE] Add search parameters to output

- .github/workflows/ci_coverage.yml
- .github/workflows/ci_linux.yml
- .github/workflows/ci_misc.yml
- .github/workflows/ci_nextflow.yml
- .github/workflows/ci_util.yml
Has same version as conda on Ubuntu jammy
> [INFRA] install ccache via apt

- include/raptor/argument_parsing/validators.hpp
- src/prepare/compute_minimiser.cpp
- test/unit/cli/search/search_hibf_preprocessing_test.cpp
> [FEATURE] Allow continuation of raptor prepare

- include/raptor/argument_parsing/build_arguments.hpp
- include/raptor/argument_parsing/timer.hpp
- include/raptor/build/hibf/insert_into_ibf.hpp
- src/build/hibf/chopper_build.cpp
- src/build/hibf/compute_kmers.cpp
- src/build/hibf/construct_ibf.cpp
- src/build/hibf/hierarchical_build.cpp
- src/build/hibf/insert_into_ibf.cpp
- src/build/hibf/loop_over_children.cpp
> [FEATURE] HIBF timing

- include/raptor/argument_parsing/build_arguments.hpp
- include/raptor/argument_parsing/memory_usage.hpp
- include/raptor/argument_parsing/prepare_arguments.hpp
- include/raptor/argument_parsing/search_arguments.hpp
- include/raptor/argument_parsing/timer.hpp
- include/raptor/argument_parsing/validators.hpp
- include/raptor/build/index_factory.hpp
- include/raptor/build/partition_config.hpp
- include/raptor/file_reader.hpp
- src/argument_parsing/search_parsing.cpp
- src/argument_parsing/upgrade_parsing.cpp
- src/search/search_partitioned_ibf.cpp
- src/threshold/precompute_correction.cpp
- test/unit/api/CMakeLists.txt
- test/unit/api/memory_usage.cpp
- test/unit/api/validate_shape.cpp
- test/unit/cli/argument_parsing/options_test.cpp
- test/unit/cli/build/build_hibf_test.cpp
- test/unit/cli/build/build_ibf_partitioned_test.cpp
- test/unit/cli/build/build_ibf_test.cpp
- test/unit/cli/search/search_hibf_preprocessing_test.cpp
- test/unit/cli/search/search_ibf_preprocessing_test.cpp
- test/unit/cli/search/search_ibf_test.cpp
> [TEST] increase coverage

- src/argument_parsing/prepare_parsing.cpp
- src/prepare/compute_minimiser.cpp
> [FEATURE] Create list file in raptor prepare

- src/argument_parsing/build_parsing.cpp
- test/data/datasources.cmake
- test/data/test.layout
- test/unit/cli/argument_parsing/options_test.cpp
- test/unit/cli/build/build_hibf_chopper_test.cpp
> [FEATURE] Read chopper layout config

- include/raptor/search/search_singular_ibf.hpp
- include/raptor/search/sync_out.hpp
- src/search/search_partitioned_ibf.cpp
> [FEATURE] Write hashes into search output

- include/raptor/build/emplace_iterator.hpp
- include/raptor/build/index_factory.hpp
> [MISC] IBF build: stream instead of caching

- util/applications/src/Genome_Biology/compare_to_truth.cpp
The cpp file is now up to date how I used it to compare the results created by our scripts (old metagraph)
> [MISC] Compare update.

- util/Genome_Biology/refseq.R
The script how I created the plot
> [FEATURE] Add R plot about Refseq timings

- src/layout/raptor_layout.cpp
- test/data/datasources.cmake
- test/data/test.layout
- test/unit/cli/build/build_hibf_chopper_test.cpp
- workflow/nextflow/hibf.nf
@eseiler there is an issue with the config serialisation. OCuld you look into that as you changes someting in chopper too (https://github.com/seqan/chopper/pull/143)
> [INFRA] Update chopper

- include/raptor/build/hibf/insert_into_ibf.hpp
- include/raptor/build/hibf/update_parent_kmers.hpp
- src/build/hibf/CMakeLists.txt
- src/build/hibf/construct_ibf.cpp
- src/build/hibf/hierarchical_build.cpp
- src/build/hibf/insert_into_ibf.cpp
- src/build/hibf/loop_over_children.cpp
- src/build/hibf/update_parent_kmers.cpp
> [MISC] Reduce complexity of insert_into_ibf.

- include/raptor/build/hibf/chopper_pack_record.hpp
- src/build/hibf/hierarchical_build.cpp
- src/build/hibf/insert_into_ibf.cpp
- src/build/hibf/parse_chopper_pack_line.cpp
- src/build/hibf/read_chopper_pack_file.cpp
- src/build/hibf/update_user_bins.cpp
This will also help to build the HIBF either from file or directly from layout records.
> [MISC] User chopper::layout::layout::user_bin in build records.

- include/raptor/build/hibf/parse_chopper_pack_header.hpp
- src/build/hibf/parse_chopper_pack_header.cpp
- src/build/hibf/read_chopper_pack_file.cpp
In the end, I want one function that reads the layout file and outputs a layout struct. And one function that create the "build-tree" from a layout struct.
> [MISC] Some restructering.

- src/CMakeLists.txt
Only install raptor executable
> [INFRA] fix install target

- src/prepare/compute_minimiser.cpp
> [FIX] Actually use all threads in raptor prepare

- .github/workflows/ci_coverage.yml
- .github/workflows/ci_linux.yml
- .github/workflows/ci_macos.yml
- .github/workflows/ci_misc.yml
- .github/workflows/ci_sanitizer.yml
- .github/workflows/ci_utility.yml
- .github/workflows/ci_workflows.yml
setup-brew via setup-toolchain prepends other path with default cmake
> [INFRA] Fix macOS CMake install

- LICENSE.md
Should reflect file header license
> [DOC] Update License

- src/prepare/compute_minimiser.cpp
> [FIX] Truncated file names in prepare

- .github/workflows/ci_sanitizer.yml
- test/unit/cli/build/build_hibf_test.cpp
- test/unit/cli/search/search_hibf_preprocessing_test.cpp
> [INFRA] Sanitizer

- .github/workflows/ci_codeql.yml
> [INFRA] Bump CodeQL

- cmake/package-lock.cmake
- src/layout/raptor_layout.cpp
- test/unit/cli/argument_parsing/options_test.cpp
Error messages should be neutral: (will also fix the unit tests)
> [INFRA] Update raptor to the latest main in the HIBF lib and chopper.
